name: yndx_homework
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: any

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  objectbox_generator: any

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
