name: yndx_homework
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_pie_chart:
    path: packages/animated_pie_chart
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.16
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  fuzzywuzzy: ^1.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.0-dev.16
  sensors_plus: ^6.1.1
  shake: ^3.0.0
  shared_preferences: ^2.5.3
  worker_manager: ^7.2.6

dev_dependencies:
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  objectbox_generator: any
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16

objectbox:
  output_dir: shared/data/datasources/local

# —— Launcher icon ——————————————————————————
flutter_launcher_icons:
  android: true # или "launcher_icon", если нужно другое имя
  ios: true
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

# —— Splash screen ——————————————————————————
flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/splash/splash.png"
  fullscreen: true
  android_screen_orientation: portrait # заменяет устаревший orientation
  android_gravity: center

  android_12: # отдельные правила для Android 12+
    image: "assets/splash/splash-android12.png"
    icon_background_color: "#ffffff"
    color: "#ffffff"

flutter:
  assets:
    - assets/icons/
  uses-material-design: true
